name: Deploy
on:
  push:
    branches:
      - master
jobs:
  deploy:
    name: Deploy to S3
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Build & create dist/artifact
        env:
          GITHUB_TOKEN: ${{ secrets.BOT_TOKEN }}
        run: |
          npm run dist
      - name: Upload Latest Version to S3
        uses: jakejarvis/s3-sync-action@master
        with:
          args: --acl public-read --follow-symlinks --delete
        env:
          AWS_S3_BUCKET: ${{ secrets.AWS_S3_BUCKET_DOWNLOADS }}
          AWS_ACCESS_KEY_ID: ${{ secrets.S3_DOWNLOADS_AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.S3_DOWNLOADS_AWS_SECRET_ACCESS_KEY }}
          SOURCE_DIR: 'artifact'      # optional: defaults to entire repository
          DEST_DIR: utils/pirate-parrot/latest
